#Rabbitmq 配置
spring:
  rabbitmq:
    #addresses: 10.0.4.140:5672, 10.0.4.143:5672
    addresses: 10.0.4.14:5672, 10.0.4.18:5672, 10.0.4.19:5672
    username: mq
    password: mq
    virtual-host: /
    port: 5672
    #    dynamic: true
    #    listener:
    #      direct:
    #        acknowledge-mode: manual
    #addresses: 172.16.1.101:5672

  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver

  #kafka配置
  kafka:
    producer:
      bootstrap-servers: 10.0.4.14:9092,10.0.4.18:9092,10.0.4.19:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: my-topic1
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: 10.0.4.14:9092,10.0.4.18:9092,10.0.4.19:9092

#mytabis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: springboot.demo.bean
  global-config:
    db-config:
      id-type: 2
      field-strategy: 2
      table-underline: true


server:
  port: 9999
