#Rabbitmq 配置
spring:
  rabbitmq:
    #addresses: 10.0.4.140:5672, 10.0.4.143:5672
    #addresses: 10.0.4.14:5672, 10.0.4.18:5672, 10.0.4.19:5672
    username: mq
    password: mq
    virtual-host: /
    port: 5672
    #    dynamic: true
    #    listener:
    #      direct:
    #        acknowledge-mode: manual
    #addresses: 172.16.1.101:5672
    host: 10.0.4.212
  #数据库配置
  datasource:
#    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&netTimeoutForStreamingResults=0
#    password: root
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&netTimeoutForStreamingResults=0&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #kafka配置
  kafka:
    producer:
      bootstrap-servers: 10.0.4.14:9092,10.0.4.18:9092,10.0.4.19:9092
      #bootstrap-servers: 172.16.13.235:9092,172.16.13.238:9092,172.16.13.240:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: my-topic1
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #bootstrap-servers: 172.16.13.235:9092,172.16.13.238:9092,172.16.13.240:9092
      bootstrap-servers: 10.0.4.14:9092,10.0.4.18:9092,10.0.4.19:9092
  #elasticsearch配置
#  elasticsearch:
#    jest:
#      uris: http://10.0.4.8:9200
  data:
    elasticsearch:
      cluster-name: uat-es-cluster-pressure
      cluster-nodes: 172.16.13.245:9300,172.16.13.246:9300,172.16.13.248:9300
  application:
    name: springboot2-nacos-config
#mytabis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: springboot.demo.bean
  global-config:
    db-config:
      id-type: 2
      field-strategy: 2
      table-underline: true

logging:
  config: classpath:config/logback.xml
server:
  port: 9999
nacos:
  config:
    server-addr: 127.0.0.1:8848
